symfony/src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\MasterData\BusinessUnit;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Hslavich\OneloginSamlBundle\Security\User\SamlUserInterface;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\AttributeOverrides({
 *     @ORM\AttributeOverride(name="password",
 *          column=@ORM\Column(
 *              name     = "password",
 *              type     = "string",
 *              nullable=true
 *          )
 *      )
 * })
 */
class User extends BaseUser implements SamlUserInterface
{
    const ROLE_ADMIN = 'ROLE_ADMIN';
    const ROLE_TRADER = 'ROLE_TRADER';
    const ROLE_BOARD_MEMBER = 'ROLE_BOARD_MEMBER';
    const ROLE_RISK_CONTROLLER = 'ROLE_RISK_CONTROLLER';
    const ROLE_BU_HEDGING_COMMITTEE = 'ROLE_BU_HEDGING_COMMITTEE';
    const ROLE_BU_MEMBER = 'ROLE_BU_MEMBER';

    public static $adminRolesChoices = [
        self::ROLE_ADMIN => 'Admin',
    ];

    public static $rolesChoices = [
        self::ROLE_TRADER => 'Trader',
        self::ROLE_BOARD_MEMBER => 'Board member',
        self::ROLE_RISK_CONTROLLER => 'Risk controller',
        self::ROLE_BU_HEDGING_COMMITTEE => 'BU hedging committee',
        self::ROLE_BU_MEMBER => 'BU Member',
    ];

    const DEFAULT_USER_FIRSTNAME = 'CYLIPOL';
    const DEFAULT_USER_LASTNAME = 'CYLIPOL';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $function;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MasterData\BusinessUnit", inversedBy="users")
     */
    private $businessUnits;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $role;

    /**
     * @var string
     * @ORM\Column(name="name_id", type="string", length=255)
     */
    public $nameId;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Pricer", mappedBy="uploadUser")
     */
    private $pricers;


    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->businessUnits = new ArrayCollection();
        $this->pricers = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFullName(): ?string
    {
        return $this->firstName . " " . $this->lastName;
    }

    /**
     * @return null|string
     */
    public function getFunction(): ?string
    {
        return $this->function;
    }

    /**
     * @param string $function
     *
     * @return User
     */
    public function setFunction(string $function): self
    {
        $this->function = $function;

        return $this;
    }

    /**
     * @return Collection|BusinessUnit[]
     */
    public function getBusinessUnits(): Collection
    {
        return $this->businessUnits;
    }

    /**
     * @param BusinessUnit $businessUnit
     *
     * @return User
     */
    public function addBusinessUnit(BusinessUnit $businessUnit): self
    {
        if (!$this->businessUnits->contains($businessUnit)) {
            $this->businessUnits[] = $businessUnit;
        }

        return $this;
    }

    /**
     * @param BusinessUnit $businessUnit
     *
     * @return User
     */
    public function removeBusinessUnit(BusinessUnit $businessUnit): self
    {
        if ($this->businessUnits->contains($businessUnit)) {
            $this->businessUnits->removeElement($businessUnit);
        }

        return $this;
    }

    /**
     * @param string|null $role
     * @return User
     */
    public function setRole(?string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getRole(): ?string
    {
        return $this->role;
    }

    /**
     * @param string $role
     * @return bool
     */
    public function hasRole($role): bool
    {
        return $this->role == $role;
    }

    public function hasCylipolRole(): bool
    {
        return $this->role ? true : false;
    }

    /**
     * @param string $nameId
     *
     * @return self
     */
    public function setNameId(string $nameId): self
    {
        $this->nameId = $nameId;

        return $this;
    }

    /**
     * @return string
     */
    public function getNameId(): ?string
    {
        return $this->nameId;
    }

    /**
     * Set SAML attributes in user object.
     *
     * @param array $attributes
     */
    public function setSamlAttributes(array $attributes): void
    {

    }

    /**
     * @return bool
     */
    public function isTrader(): bool
    {
        return $this->hasRole(self::ROLE_TRADER);
    }

    /**
     * @return bool
     */
    public function isBoardMember(): bool
    {
        return $this->hasRole(self::ROLE_BOARD_MEMBER);
    }

    /**
     * @return bool
     */
    public function isRiskController(): bool
    {
        return $this->hasRole(self::ROLE_RISK_CONTROLLER);
    }

    /**
     * @return bool
     */
    public function isBuHedgingCommittee(): bool
    {
        return $this->hasRole(self::ROLE_BU_HEDGING_COMMITTEE);
    }

    /**
     * @return bool
     */
    public function isBuMember(): bool
    {
        return $this->hasRole(self::ROLE_BU_MEMBER);
    }

    /**
     * @return bool
     */
    public function isAdmin(): bool
    {
        return in_array('ROLE_ADMIN', $this->getRoles());
    }

    /**
     * @return Collection|Pricer[]
     */
    public function getPricers(): Collection
    {
        return $this->pricers;
    }

    public function addPricer(Pricer $pricer): self
    {
        if (!$this->pricers->contains($pricer)) {
            $this->pricers[] = $pricer;
            $pricer->setUploadUser($this);
        }

        return $this;
    }

    public function removePricer(Pricer $pricer): self
    {
        if ($this->pricers->contains($pricer)) {
            $this->pricers->removeElement($pricer);
            // set the owning side to null (unless already changed)
            if ($pricer->getUploadUser() === $this) {
                $pricer->setUploadUser(null);
            }
        }

        return $this;
    }
}

symfony/templates/common/alerts.html.twig
<aside class="aside-alerts-wrap">
  <a href="javascript:void(0)" class="btn-alert"><i class="icon-bell"></i></a>

  <!-- Tab Alerts -->
  <ul class="tab-alerts-nav list-inline">
    <li class="list-inline-item">
      <a href="javascript:void(0)" class="tab-hedge-alerts active">{{ 'alerts.hedge.title' | trans }}{% if hedgeAlertsNotViewedCount %}<span class="number-alerts hedge">({{ hedgeAlertsNotViewedCount }})</span>{% endif %}</a>
    </li>
    {% if is_granted('alert_rmp') %}
      <li class="list-inline-item">
        <a href="javascript:void(0)"  class="tab-rmp-alerts">{{ 'alerts.rmp.title' | trans }}{% if rmpAlertsNotViewedCount %}<span class="number-alerts rmp">({{ rmpAlertsNotViewedCount }})</span>{% endif %}</a>
      </li>
    {% endif %}
  </ul>

  <!-- List -->
  <ul class="list-alerts list-unstyled hedge-alerts">
    {% for hedgeAlertUser in hedgeAlertsUser%}
      <li class="alert {{ not hedgeAlertUser.isViewed ? 'not-viewed' : ''}} {{ not hedgeAlertUser.isRead ? 'unread' : ''}} {% if is_granted('hedge_edit', hedgeAlertUser.alert.parent) %}alert-clickable{% endif %}">
        <a href="javascript:void(0)" data-url="{{ path('hedge_edit', {'hedge': hedgeAlertUser.alert.parent.id}) }}" class="alert-block"
           data-bu-id="{{ hedgeAlertUser.alert.parent.rmp.businessUnit.id }}" data-id="{{ hedgeAlertUser.id }}" data-type="hedge">
          <div class="alert-date">{{ hedgeAlertUser.alert.timestamp|date('m/d/Y') }} - {{ hedgeAlertUser.alert.timestamp|date('g:i a') }}</div>
          <div class="alert-text">{{ hedgeAlertsLabels[hedgeAlertUser.alert.type]|trans({'%hedgeId%': hedgeAlertUser.alert.parent.id, '%buName%': hedgeAlertUser.alert.parent.rmp.businessUnit, '%hedgeStatus%': hedgeStatusLabels[hedgeAlertUser.alert.parent.status]|trans}) }}</div>
          {% if hedgeAlertUser.alert.additionalMessage %}
            <div class="alert-text additional-message {% if hedgeAlertUser.alert.type != constant('App\\Entity\\HedgeAlert::TYPE_COMMENT') %}italic{% endif %}">
                {{ hedgeAlertUser.alert.additionalMessage|striptags|length > 60 ? hedgeAlertUser.alert.additionalMessage|slice(0,60)|raw : hedgeAlertUser.alert.additionalMessage|raw }}
                {{ hedgeAlertUser.alert.additionalMessage|striptags|length > 60 ? '...' : ''}}
            </div>
          {% endif %}
          {% if is_granted('hedge_edit', hedgeAlertUser.alert.parent) %}
            <div class="btn btn-secondary">{{ 'alerts.hedge.button'|trans }}</div>
          {% endif %}
        </a>
        <a href="javascript:void(0)" class="alert-delete"><i class="zmdi zmdi-close"></i></a>
      </li>
    {% endfor %}
  </ul>
  {% if is_granted('alert_rmp') %}
    <ul class="list-alerts list-unstyled rmp-alerts d-none">
      {% for rmpAlertUser in rmpAlertsUser %}
        <li class="alert {{ not rmpAlertUser.isViewed ? 'not-viewed' : ''}} {{ not rmpAlertUser.isRead ? 'unread' : ''}} {% if is_granted('rmp_view', rmpAlertUser.alert.parent) %}alert-clickable{% endif %}">
          <a href="javascript:void(0)" data-url="{{ path('rmp_view', {'rmp': rmpAlertUser.alert.parent.id}) }}" class="alert-block"
             data-bu-id="{{ rmpAlertUser.alert.parent.businessUnit.id }}" data-id="{{ rmpAlertUser.id }}" data-type="rmp">
            <div class="alert-date">{{ rmpAlertUser.alert.timestamp|date('m/d/Y') }} - {{ rmpAlertUser.alert.timestamp|date('g:i a') }}</div>
            <div class="alert-text">{{ rmpAlertsLabels[rmpAlertUser.alert.type]|trans({'%rmpName%': rmpAlertUser.alert.parent.name, '%validityPeriod%': rmpAlertUser.alert.parent.validityPeriod}) }}</div>
            {% if rmpAlertUser.alert.additionalMessage %}
              <div class="alert-text additional-message {% if rmpAlertUser.alert.type != constant('App\\Entity\\RmpAlert::TYPE_COMMENT') %}italic{% endif %}">
                  {{ rmpAlertUser.alert.additionalMessage|striptags|length > 60 ? rmpAlertUser.alert.additionalMessage|slice(0,60)|raw : rmpAlertUser.alert.additionalMessage|raw }}
                  {{ rmpAlertUser.alert.additionalMessage|striptags|length > 60 ? '...' : ''}}
              </div>
            {% endif %}
            <div class="btn btn-secondary">{{ 'alerts.rmp.button'|trans }}</div>
          </a>
          <a href="javascript:void(0)" class="alert-delete"><i class="zmdi zmdi-close"></i></a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</aside>

symfony/templates/common/bootstrap_4_layout.html.twig
{% use "form_div_layout.html.twig" %}

{# Widgets #}
{% block textarea_widget -%}
    {% set attr = attr|merge({class: (attr.class|default('') ~ ' form-control')|trim}) %}
    {{- parent() -}}
{%- endblock textarea_widget %}

{% block button_widget -%}
    {% set attr = attr|merge({class: (attr.class|default('btn-default') ~ ' btn')|trim}) %}
    {{- parent() -}}
{%- endblock %}


{% block form_widget_simple -%}
    {% if type is defined and type == 'file' %}
        <input type="file" name="{{ full_name }}" id="{{ id }}" class="form-file" data-multiple-caption="">
        <label for="{{ id }}"><span>{{ 'thumbable.chooseFile'|trans }}</span> <strong>{{ 'thumbable.browse'|trans }}</strong></label>
    {% elseif type is defined and type == 'date' %}
        <input class="form-control jsdatepicker" type="text" class="form-control" id="{{ id }}" value="{{ value }}" name="{{ full_name }}" {% if required %}required{% endif %}>
    {% else %}
      {% if type is not defined or type not in ['file', 'hidden'] %}
        {%- set attr = attr|merge({class: (attr.class|default('') ~ ' form-control')|trim}) -%}
      {% endif %}
      {{- parent() -}}
    {% endif %}
{%- endblock form_widget_simple %}


{% block money_widget -%}
    <div class="input-group">
        {% set append = money_pattern starts with '{{' %}
        {% if not append %}
            <span class="input-group-addon">{{ money_pattern|replace({ '{{ widget }}':''}) }}</span>
        {% endif %}
        {{- block('form_widget_simple') -}}
        {% if append %}
            <span class="input-group-addon">{{ money_pattern|replace({ '{{ widget }}':''}) }}</span>
        {% endif %}
    </div>
{%- endblock money_widget %}

{% block percent_widget -%}
    <div class="input-group">
        {{- block('form_widget_simple') -}}
        <span class="input-group-addon">%</span>
    </div>
{%- endblock percent_widget %}

{% block datetime_widget -%}
    {% if widget == 'single_text' %}
        {%- if attr.type is defined -%}{% set type = attr.type %}{%- endif -%}
        {{- block('form_widget_simple') -}}
    {% else -%}
        {% set attr = attr|merge({class: (attr.class|default('') ~ ' form-inline')|trim}) -%}
        <div {{ block('widget_container_attributes') }}>
            {{- form_errors(form.date) -}}
            {{- form_errors(form.time) -}}
            {{- form_widget(form.date, { datetime: true } ) -}}
            {{- form_widget(form.time, { datetime: true } ) -}}
        </div>
    {%- endif %}
{%- endblock datetime_widget %}

{% block date_widget -%}
    {% if widget == 'single_text' %}
        {{- block('form_widget_simple') -}}
    {% else -%}
        {% set attr = attr|merge({class: (attr.class|default('') ~ ' form-inline')|trim}) -%}
        {% if datetime is not defined or not datetime -%}
            <div {{ block('widget_container_attributes') -}}>
        {%- endif %}
        {{- date_pattern|replace({
            '{{ year }}': form_widget(form.year),
            '{{ month }}': form_widget(form.month),
            '{{ day }}': form_widget(form.day),
        })|raw -}}
        {% if datetime is not defined or not datetime -%}
            </div>
        {%- endif -%}
    {% endif %}
{%- endblock date_widget %}

{% block time_widget -%}
    {% if widget == 'single_text' %}
      <input class="form-control jstimepicker" type="text" class="form-control" id="{{ id }}" value="{{ value }}" name="{{ full_name }}" {% if required %}required{% endif %}>
    {% else -%}
        {% set attr = attr|merge({class: (attr.class|default('') ~ ' form-inline')|trim}) -%}
        {% if datetime is not defined or false == datetime -%}
            <div {{ block('widget_container_attributes') -}}>
        {%- endif -%}
        {{- form_widget(form.hour) }}{% if with_minutes %}:{{ form_widget(form.minute) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second) }}{% endif %}
        {% if datetime is not defined or false == datetime -%}
            </div>
        {%- endif -%}
    {% endif %}
{%- endblock time_widget %}

{% block choice_widget_collapsed -%}
    {% set customChoiceClass = attr|merge({class: (attr.class|default(''))|trim}) %}
    {% set attr = attr|merge({class: (attr.class|default('') ~ ' form-control')|trim}) %}
    {% set customEntity = attr.customEntity|default(false) %}

    {% if customEntity %}
        {% set index = form.parent.value.vars.id|split('_') %}
        {% for parent in form.parent.value.vars.choices %}
          {% set i = loop.index %}
          {% set scale = form.parent.value.vars.choices[i].data %}
          {% if scale.hasChildren or (scale.code|length and not scale.hasChildren and not scale.parent) %}
            <div class="panel">
              <div class="panel-title {{ customChoiceClass.class }}">
                <a class="link-panel" data-toggle="collapse" href="#collapse{{ index[1] }}-{{ i }}" role="button" aria-expanded="{{ scale.isExpanded(form.parent.value.vars.value) }}" aria-controls="collapse{{ index[1] }}-{{ i }}">
                  &nbsp;
                </a>
                <div class="form-checkbox">
                  <input type="checkbox" id="{{ index[1] }}-{{ i }}" name="fields[{{ index[1] }}][{{ form.parent.value.vars.name }}][]" value="{{ scale.id }}" class="toggle-all" {% if scale.id in form.parent.value.vars.value %}checked{% endif %}>
                  <label for="{{ index[1] }}-{{ i }}">
                    <span class="icon"></span>
                    <span>{{ scale }}</span>
                  </label>
                </div>
              </div>
              <div class="panel-content collapse {% if scale.isExpanded(form.parent.value.vars.value) %}show{% endif %}" id="collapse{{ index[1] }}-{{ i }}">
                <div class="row">
                  {% for child in scale.children %}
                    {% set j = loop.index %}
                    <div class="col-3">
                      <div class="form-checkbox">
                        <input type="checkbox" name="fields[{{ index[1] }}][{{ form.parent.value.vars.name }}][]" id="{{ index[1] }}-{{ i }}-{{ j }}" value="{{ child.id }}" {% if child.id in form.parent.value.vars.value %}checked{% endif %}>
                        <label for="{{ index[1] }}-{{ i }}-{{ j }}">
                          <span class="icon"></span>
                          <span class="label-align">{{ child }}</span>
                        </label>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endif %}
        {% endfor %}
    {% else %}
        <div class="form-select">
            {{- parent() -}}
        </div>
    {% endif %}
{%- endblock %}

{% block choice_widget_expanded -%}
    {% if '-inline' in label_attr.class|default('') -%}
        {%- for child in form %}
            {{- form_widget(child, {
                parent_label_class: label_attr.class|default(''),
                translation_domain: choice_translation_domain,
            }) -}}
        {% endfor -%}
    {%- elseif 'special-thumbable' in type|default('') -%}
        <div class="form-radio-special" {{ block('widget_container_attributes') }}>
            {%- for child in form %}
                {{- form_widget(child, {
                    parent_label_class: label_attr.class|default(''),
                    translation_domain: choice_translation_domain,
                    type: type
                }) -}}
            {% endfor -%}
        </div>
    {%- else -%}
        {#<div {{ block('widget_container_attributes') }}>#}
            {%- for child in form %}
                {{- form_widget(child, {
                    parent_label_class: label_attr.class|default(''),
                    translation_domain: choice_translation_domain,
                }) -}}
            {% endfor -%}
        {#</div>#}
    {%- endif %}
{%- endblock choice_widget_expanded %}

{% block checkbox_widget -%}
    {%- set parent_label_class = parent_label_class|default(label_attr.class|default('')) -%}
    {% if 'checkbox-inline' in parent_label_class %}
        {{- form_label(form, null, { widget: parent() }) -}}
    {% else -%}
        <div class="form-checkbox">
            {{- form_label(form, null, { widget: parent() }) -}}
        </div>
    {%- endif %}
{%- endblock checkbox_widget %}

{% block radio_widget -%}
    {%- set parent_label_class = parent_label_class|default(label_attr.class|default('')) -%}
    {% if 'radio-inline' in parent_label_class %}
        {{- form_label(form, null, { widget: parent() }) -}}
    {% else -%}

        <div class="form-radio">
            {{- form_label(form, null, { widget: parent() }) -}}
        </div>

    {%- endif %}
{%- endblock radio_widget %}

{# Labels #}

{% block form_label -%}
    {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' control-label')|trim}) -%}
    {{- parent() -}}
{%- endblock form_label %}

{% block choice_label -%}
    {# remove the checkbox-inline and radio-inline class, it's only useful for embed labels #}
    {%- set label_attr = label_attr|merge({class: label_attr.class|default('')|replace({'checkbox-inline': '', 'radio-inline': ''})|trim}) -%}
    {{- block('form_label') -}}
{% endblock %}



{% block checkbox_label -%}
    {{- block('checkbox_radio_label') -}}
{%- endblock checkbox_label %}

{% block radio_label -%}
    {{- block('checkbox_radio_label') -}}
{%- endblock radio_label %}

{% block checkbox_radio_label %}
    {# Do not display the label if widget is not defined in order to prevent double label rendering #}
    {% if widget is defined %}
        {% if required %}
            {% set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' required')|trim}) %}
        {% endif %}
        {% if parent_label_class is defined %}
            {% set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' ' ~ parent_label_class)|trim}) %}
        {% endif %}
        {% if label is not same as(false) and label is empty %}
            {%- if label_format is not empty -%}
                {% set label = label_format|replace({
                '%name%': name,
                '%id%': id,
                }) %}
            {%- else -%}
                {% set label = name|humanize %}
            {%- endif -%}
        {% endif %}
        {% if 'special-thumbable' in type|default('') %}
            {{- widget|raw }}
            <label {% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %} for={{ id }}>
                <i class="zmdi zmdi-{{ label|lower == 'video' ? 'videocam' : label|lower }}"></i><span>{{ label is not same as(false) ? (translation_domain is same as(false) ? label : label|trans({}, translation_domain)) -}}</span> <span class="icon"></span>
            </label>
        {% else %}
            {{- widget|raw }}
            <label {% for attrname, attrvalue in label_attr %} {% if not (attrname == 'class' and attrvalue == 'required') %} {{ attrname }}="{{ attrvalue }}"{% endif %} {% endfor %} for={{ id }}>
                <span class="icon"></span> <span class="label-align">{{ label is not same as(false) ? (translation_domain is same as(false) ? label : label|trans({}, translation_domain)) -}}</span>
            </label>
        {% endif  %}

    {% endif %}
{% endblock checkbox_radio_label %}

{# Rows #}

{% block form_row -%}
    {% set customClass = attr.customClass|default('') %}

    <div class="form-group {{ customClass }}{% if (not compound or force_error|default(false)) and not valid %} has-error{% endif %}">
        {{- form_label(form) -}}
        {% if customClass == 'col-12 col-radio' %}
            <div class="form-content-radio"> {{- form_widget(form) -}} </div>
        {% else %}
            {{- form_widget(form) -}}
        {% endif %}
        {{- form_errors(form) -}}
    </div>
{%- endblock form_row %}

{% block button_row -%}
    <div class="form-group">
        {{- form_widget(form) -}}
    </div>
{%- endblock button_row %}

{% block choice_row -%}
    {% set force_error = true %}
    {{- block('form_row') }}
{%- endblock choice_row %}

{% block date_row -%}
    {% set force_error = true %}
    {{- block('form_row') }}
{%- endblock date_row %}

{% block time_row -%}
    {% set force_error = true %}
    {{- block('form_row') }}
{%- endblock time_row %}

{% block datetime_row -%}
    {% set force_error = true %}
    {{- block('form_row') }}
{%- endblock datetime_row %}

{% block checkbox_row -%}
    <div class="form-group{% if not valid %} has-error{% endif %}">
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>
{%- endblock checkbox_row %}

{% block radio_row -%}
    <div class="form-group col-12{% if not valid %} has-error{% endif %}">
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>
{%- endblock radio_row %}

{# Errors #}

{% block form_errors -%}
    {% if errors|length > 0 -%}
        {% if form.parent %}<small class="form-text text-danger">{% else %}<div class="alert alert-danger">{% endif %}
        {% if errors|length > 1 %}
            <ul class="list-unstyled">
                {%- for error in errors -%}
                  <li>
                      <span class="glyphicon glyphicon-exclamation-sign"></span> {{ error.message }}
                  </li>
                {%- endfor -%}
            </ul>
        {% else %}
          {%- for error in errors -%}
            {{ error.message }}
          {%- endfor -%}
        {% endif %}
        {% if form.parent %}</small>{% else %}</div>{% endif %}
    {%- endif %}
{%- endblock form_errors %}

symfony/templates/common/header.html.twig
<header class="header-middle-wrap no-print">
  <div class="header-title">{{ 'app.title' | trans }}</div>

  <!-- Logo -->
  <a href="{{ path('homepage') }}" class="header-logo">
    <img src="{{ asset('img/SHV_default.svg') }}" alt="SHV GAS" >
  </a>

  <!-- Button Alerts -->
  <a href="javascript:void(0)" class="btn-alert">
    <i class="icon-bell"></i><span class="sr-only">{{ 'notifications' | trans }}</span>
    {% if alertsCount %}
      <span class="number-alerts hedge rmp">{{ alertsCount }}</span>
    {% endif %}
  </a>

  <!-- User -->
  <div class="user-block">
    <div class="user-id-info">
      <div class="user-id-welcome"><strong>{{ 'hello' | trans }},</strong>
        <div class="dropdown">
          <button class="btn btn-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ app.user.firstName }} {{ app.user.lastName }} <i class="zmdi zmdi-chevron-down"></i>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% if dev %}
              <a class="dropdown-item" href="{{ path('fos_user_security_logout') }}">{{ 'sign_out' | trans }}</a>
            {% else %}
              <a class="dropdown-item" href="{{ path('saml_logout') }}">{{ 'sign_out' | trans }}</a>
            {% endif %}
            {% if app.user.isAdmin %}
              <a class="dropdown-item" href="{{ path('sonata_admin_dashboard') }}">{{ 'back_office' | trans }}</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="user-status">{{ app.user.function }}</div>
    </div>
  </div>

  <!-- Select -->
  {% if app.user.isBuHedgingCommittee and app.user.businessUnits|length > 1 %}
    <div class="form-group form-type-group">
      <div class="form-select">
        <select id="header-bu-selector" class="form-control">
          {% for bu in app.user.businessUnits %}
          <option value="{{ bu.id }}" {% if selected_business_unit.id == bu.id %}selected{% endif %}>{{ bu.fullName }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
  {% endif %}
</header>